### ISSUE TITLE
gridsome-remark-katex doesn't work with vue-remark

### ISSUE THREAD

**Issue by sayedessam** [pchorus/gridsome-remark-katex#1] opened 2020-01-18 18:14 UTC
I'm trying to use gridsome-remark-katex with vue-remark, but the math equation doesn't show

module.exports = {
  siteName: 'Gridsome',
  plugins: [
    {
      use: '@gridsome/vue-remark',
      options: {
        typeName: 'Documentation', // Required
        baseDir: './src/content/docs', // Where .md files are located
        pathPrefix: '/docs', // Add route prefix. Optional
        template: './src/templates/Documentation.vue' // Optional
        
      }
    }
  ],
  transformers: {
    remark: {
      plugins: [
        'gridsome-remark-katex'
      ]
    }
  }

**Comment by pchorus** [comment] 2020-01-19 19:18
Hi @sayedessam,

thanks for posting this issue. Could you please provide a minimal reproducible example so I can check the problem and fix it?

Thanks in advance.

**Comment by pchorus** [comment] 2020-03-03 13:38
@sayedessam Is this still an issue? Otherwise I would close this issue.

**Comment by pchorus** [comment] 2020-06-02 19:53
Closed because there is no activity.

**Closed** 2020-06-02 19:52 UTC
